version: "3.9"

services:
  relayer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
  lodestar-light-client:
    image: limechain/lodestar-wisp:1.2
    command:
      - 'lightclient'
      - '--network'
      - 'goerli'
      - '--beaconApiUrl=https://lodestar-goerli.chainsafe.io'
      - '--checkpointRoot=${CHECKPOINT_ROOT}'
      - '--crcApiUrl=http://relayer:8080'
    depends_on: [relayer]
    restart: always
