server:
  port: 3000
lightClient:
  genesisTime: 1616508000
  beaconNode:
    url:
  prover:
    url:
  networks:
    - name: 'Goerli'
      rpcUrl:
      contractAddress: '0x78a8de9fef87777afabc4862c99f91a1d54d09f8'
      privateKey:
mongodb:
  uri: '<connection string>'